import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useSelector, useDispatch } from 'react-redux'
import Image from 'next/image'
// import { decrement, increment } from '../slices/counterSlice'
import HomePageHeroSection from '../components/HomePageHeroSection'

export default function Home() {

  const count = useSelector(state => state.counter.value)
  const dispatch = useDispatch()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomePageHeroSection/>
      </main>
    </div>
  )
}
