import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useSelector, useDispatch } from 'react-redux'
import { decrement, increment } from '../slices/counterSlice'

export default function Home() {

  const count = useSelector(state => state.counter.value)
  const dispatch = useDispatch()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Home Page</h2>


        {/* <div className="row">
          <div className="container mx-auto">

            <button
              aria-label="Increment value"
              onClick={() => dispatch(increment())}
              className={"bg-red-400 py-2 px-6"}
            >
              Increment
            </button>
            <span className={"font-bold text-6xl"}>{count}</span>
            <button
              aria-label="Decrement value"
              onClick={() => dispatch(decrement())}
              className={"bg-blue-400 py-2 px-6"}
            >
              Decrement
            </button>
          </div>
        </div> */}
      </main>
    </div>
  )
}
